# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  version: "0.13"

  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: onomondo
      url-base: https://github.com/onomondo

  projects:
    - name: sdk-nrf
      revision: v3.1.0
      path: nrf
    - name: sdk-zephyr
      revision: v4.0.99-ncs1-2
      path: zephyr
    - name: sdk-mcuboot
      revision: v2.1.0-ncs5-2
      path: bootloader/mcuboot
    - name: sdk-mbedtls
      revision: v3.6.3-ncs1-2
      path: modules/crypto/mbedtls
    - name: sdk-nrfxlib
      revision: v3.0.2
      path: nrfxlib
    - name: sdk-trusted-firmware-m
      revision: v2.1.1-ncs4-2
      path: modules/tee/tf-m/trusted-firmware-m
    - name: onomondo-softsim
      remote: onomondo
      revision: main
      path: modules/lib/onomondo-softsim

  self:
    path: thingy91-demo